define(function(require) {
    return {
        testCases:{
          "1":{"description":"Einstein's Equation","testCase":[{"type":"Symbol","position":{"x":367.81,"y":304},"expression":{"latex":"E = mc^{2}","python":"E == m*c**(2)"},"children":{"right":{"type":"Relation","children":{"right":{"type":"Symbol","children":{"right":{"type":"Symbol","children":{"superscript":{"type":"Num","properties":{"significand":"2"}}},"properties":{"letter":"c"}}},"properties":{"letter":"m"}}},"properties":{"relation":"="}}},"properties":{"letter":"E"}}]},
          "2":{"description":"Euler's Identity","testCase":[{"type":"Symbol","position":{"x":368.58,"y":302},"expression":{"latex":"e^{iπ} + 1 = 0","python":"e**(i*π) +1 == 0"},"children":{"right":{"type":"BinaryOperation","children":{"right":{"type":"Num","children":{"right":{"type":"Relation","children":{"right":{"type":"Num","properties":{"significand":"0"}}},"properties":{"relation":"="}}},"properties":{"significand":"1"}}},"properties":{"operation":"+"}},"superscript":{"type":"Symbol","children":{"right":{"type":"Symbol","properties":{"letter":"π"}}},"properties":{"letter":"i"}}},"properties":{"letter":"e"}}]},
          "3":{"description":"Newton's Law of Gravitation","testCase":[{"type":"Symbol","position":{"x":374.425,"y":315},"expression":{"latex":"F =  - \\frac{GMm}{r^{2}}","python":"F ==  -((G*M*m)/(r**(2)))"},"children":{"right":{"type":"Relation","children":{"right":{"type":"BinaryOperation","children":{"right":{"type":"Fraction","children":{"numerator":{"type":"Symbol","children":{"right":{"type":"Symbol","children":{"right":{"type":"Symbol","properties":{"letter":"m"}}},"properties":{"letter":"M"}}},"properties":{"letter":"G"}},"denominator":{"type":"Symbol","children":{"superscript":{"type":"Num","properties":{"significand":"2"}}},"properties":{"letter":"r"}}}}},"properties":{"operation":"−"}}},"properties":{"relation":"="}}},"properties":{"letter":"F"}}]}
        }
    }
});
