#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "Usage: compose-staging2 staging2 VERSION"
    exit 1
fi

ENV=$1
APP_VERSION=$2

shift 2

if [ $1 = "create" ] || [ $1 = "exec" ] || [ $1 = "pull" ] || [ $1 = "push" ] || [ $1 = "run" ] || [ $1 = "start" ] || [ $1 = "up" ]; then
  docker pull docker.isaacscience.org/isaac-phy-app:$APP_VERSION
fi

APP_NAME=phy-app-$ENV-$APP_VERSION

if [ "$ENV" == "staging2" ]; then
  : # Continue
else
  echo "Must set environment to staging2!"
  exit 1
fi

cat << EOF | docker-compose -p dc-$APP_NAME -f - $@
version: '2'
services:
  $APP_NAME:
    container_name: $APP_NAME
    image: docker.isaacscience.org/isaac-phy-app:$APP_VERSION
    restart: unless-stopped
    networks:
      default:
        aliases:
          - phy-app-$ENV
networks:
  default:
    external:
      name: isaac

EOF

exit 0
