version: '2'
services:
  app-physics:
    network_mode: bridge
    container_name: app-physics
    image: nginx:stable
    volumes:
      - "./app:/usr/share/nginx/html:ro"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "8000:80"
networks:
  default:
    external:
      name: bridge
