FROM ubuntu:xenial

RUN apt-get update
RUN apt-get install -y ca-certificates curl openssl git
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -yy nodejs
RUN npm install -g grunt-cli

ENV DOCKER_BUCKET get.docker.com
ENV DOCKER_VERSION 1.12.1
ENV DOCKER_SHA256 05ceec7fd937e1416e5dce12b0b6e1c655907d349d52574319a1e875077ccb79

RUN set -x \
	&& curl -fSL "https://${DOCKER_BUCKET}/builds/Linux/x86_64/docker-${DOCKER_VERSION}.tgz" -o docker.tgz \
	&& echo "${DOCKER_SHA256} *docker.tgz" | sha256sum -c - \
	&& tar -xzvf docker.tgz \
	&& mv docker/* /usr/local/bin/ \
	&& rmdir docker \
	&& rm docker.tgz \
	&& docker -v



COPY ./build.sh /build.sh

CMD ["./build.sh"]
